04_Paturâge/merchex_django/merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.band_list, name="band-list"),
    path('bands/<int:id>/', views.band_detail, name="band-detail"),
    path('bands/<int:id>/change/', views.band_change, name="band-change"),
    path('bands/<int:id>/delete/', views.band_delete, name="band-delete"),
    path('bands/add/', views.band_create, name="band-create"),
    path('about-us/', views.about, name="about"),
    path('contact-us', views.contact, name="contact"),
    path('annonces', views.listings_list, name='listings-list'),
    path('title/<int:id>/', views.listings_detail, name="listings-detail"),
    path('annonces/add/', views.listings_create, name="listings-create"),
    path('title/<int:id>/change/', views.listings_change, name='listings-change'),
    path('title/<int:id>/delete/', views.listings_delete, name='listings-delete'),
    path('email_sent.html', views.email_sent)

]

04_Paturâge/merchex_django/merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Band(models.Model):
    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = "AR"
        POP_ROCK = "PR"

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2022)])
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    def __str__(self):
        return f'{self.name}'


class Title(models.Model):
    class Type(models.TextChoices):
        DISQUE = 'Disque'
        VETEMENT = 'Vêtement'
        POSTERS = 'POSTERS'
        DIVERS = 'DIVERS'

    name_title = models.fields.CharField(max_length=300)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2022)]
    )
    type = models.fields.CharField(choices=Type.choices, max_length=15)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

04_Paturâge/merchex_django/merchex/listings/forms.py
from django import forms

from listings.models import Band, Title


class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)


class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        fields = '__all__'


class TitleForm(forms.ModelForm):
    class Meta:
        model = Title
        fields = '__all__'

04_Paturâge/merchex_django/merchex/listings/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.shortcuts import redirect

from listings.models import Band
from listings.models import Title
from listings.forms import ContactUsForm, BandForm, TitleForm


"""
Page de l'application
"""

def band_list(request):
    bands = Band.objects.all()
    return render(request, 'listings/band_list.html',
                  {'bands': bands})


def band_detail(request, id):
    band = Band.objects.get(id=id)
    return render(request, 'listings/band_detail.html',
                  {'band': band})


def listings_list(request):
    titles = Title.objects.all()
    return render(request, 'listings/listings_list.html',
                  {'titles': titles})


def listings_detail(request, id):
    title = Title.objects.get(id=id)
    return render(request, 'listings/listings_detail.html',
                  {'title': title})


def about(request):
    return render(request, 'listings/about.html')

"""
Contact form
"""

def contact(request):
    #print('La méthode de requête est : ', request.method)
    #print('Les données POST sont : ', request.POST)

    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(
                subject=f"Message from {form.cleaned_data['name'] or 'anonyme'} via MerchEx Contact Us form",
                message=form.cleaned_data["message"],
                from_email=form.cleaned_data['email'],
                recipient_list=['admin@merchex.xyz']
            )
        return redirect('email_sent.html')
    else:
        form = ContactUsForm()

    return render(request, 'listings/contact.html',
                  {'form': form})


def email_sent(request):
    return render(request, 'listings/email_sent.html')

"""
CRUD CREATE
"""

def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            band = form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm()

    return render(request, 'listings/band_create.html',
                  {'form': form})


def listings_create(request):
    if request.method == 'POST':
        form = TitleForm(request.POST)
        if form.is_valid():
            title = form.save()
            return redirect('listings-detail', title.id)
    else:
        form = TitleForm()

    return render(request, 'listings/listings_create.html',
                  {'form': form})


"""
CRUD UPDATE
"""

def band_change(request, id):
    band = Band.objects.get(id=id)

    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance=band)

    return render(request, 'listings/band_change.html',
                  {'form': form})


def listings_change(request, id):
    title = Title.objects.get(id=id)

    if request.method == "POST":
        form = TitleForm(request.POST, instance=title)
        if form.is_valid():
            form.save()
            return redirect('listings-detail', title.id)
    else:
        form = TitleForm(instance=title)

    return render(request, 'listings/listings_change.html',
                  {'form': form})


"""
CRUD DELETE
"""


def band_delete(request, id):
    band = Band.objects.get(id=id)

    if request.method == "POST":
        band.delete()
        return redirect('band-list')

    return render(request, 'listings/band_delete.html',
                  {'band': band})


def listings_delete(request, id):
    title = Title.objects.get(id=id)

    if request.method == "POST":
        title.delete()
        return redirect('listings-list')

    return render(request, 'listings/listings_delete.html',
                  {'title': title})

04_Paturâge/merchex_django/merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>A propos de nous</h1>

<p>OpenClassrooms est un site web de formation en ligne, créé en 1999 sous le nom de Site du Zéro. </p>

<p>Il propose à ses membres des cours certifiants et des parcours débouchant sur des métiers en croissance.</p>

<p>Initialement orientée autour de la programmation informatique, la plate-forme numérique couvre, depuis 2013, d'autres thématiques telles que l'entrepreneuriat et le marketing électronique.</p>

<p>Ses formations sont dispensées selon le format MOOC. </p>

{% endblock %}

04_Paturâge/merchex_django/merchex/listings/templates/listings/band_change.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Mise à jour du groupe</h1>

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Envoyer" class="send">
</form>

{% endblock %}

04_Paturâge/merchex_django/merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Créer un nouveau groupe</h1>

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Envoyer" class="send">
</form>

{% endblock %}

04_Paturâge/merchex_django/merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Supprimer le groupe</h1>

<p>Etes-vous sûr de vouloir supprimer le groupe : {{band.name}} ?</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Supprimer" class="send_del">
</form>

{% endblock %}

04_Paturâge/merchex_django/merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}
<h2>{{band.name}}</h2>

<ul>
    <li>Genre : {{band.get_genre_display}}</li>
    <li>Année de formation : {{band.year_formed}}</li>
    <li>Actif : {{band.active|yesno}}</li>
    <li><a href="{{band.official_homepage}}">{{band.official_homepage}}</a></li>
</ul>

<p class="biography">{{band.biography}}</p>

<a href="{% url 'band-change' band.id %}">Modifier ce groupe</a>

<a href="{% url 'band-delete' band.id %}">Supprimer ce groupe</a>

<a href="{% url 'band-list' %}" class="return">Retour aux différents groupes</a>
{% endblock %}

04_Paturâge/merchex_django/merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Groupes</h1>

<a href="{% url 'band-create' %}">Créer un nouveau groupe</a>

<p class="link">Voici la liste des groupes présents :</p>

<div class="liste">
    <ul>
    {% for band in bands%}
        <li>
            <a href="{% url 'band-detail' band.id %}">{{band.name}}</a>
            - <a href="{% url 'band-change' band.id %}">[Modifier]</a>
        </li>
    {% endfor %}
    </ul>
</div>

{% endblock %}

04_Paturâge/merchex_django/merchex/listings/templates/listings/base.html
{% load static %}

<html lang="fr">
    <head>
        <meta name="auteur" content="Loïc Calcagno">
        <meta name="description" content="Site web créé à partir du framework Django">
        <title>Merchex</title>
        <link rel="stylesheet" href="{% static 'listings/styles.css' %}"/>
        <link rel="icon" href="https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg">
    </head>
    <body>
        <nav>
            <a href="{% url 'band-list' %}">Groupes</a>
            <a href="{% url 'listings-list' %}">Annonces</a>
            <a href="{% url 'contact' %}">Contact</a>
            <a href="{% url 'about' %}">A propos de nous</a>
            <a href="admin/">Administration</a>
        </nav>

        {% block content %}

        {% endblock %}
    </body>
</html>

04_Paturâge/merchex_django/merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Contactez nous!</h1>

<p>Nous sommes là pour vous aider!</p>

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Envoyer" class="send">
</form>

{% endblock %}

04_Paturâge/merchex_django/merchex/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Votre email a bien été envoyé!</h1>

<a href="{% url 'band-list' %}">Retour sur le site</a>

{% endblock %}

04_Paturâge/merchex_django/merchex/listings/templates/listings/listings_change.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Modifier une annonce</h1>

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Envoyer" class="send">
</form>

{% endblock %}

04_Paturâge/merchex_django/merchex/listings/templates/listings/listings_create.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Créer une nouvelle annonce</h1>

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Envoyer" class="send">
</form>

{% endblock %}

04_Paturâge/merchex_django/merchex/listings/templates/listings/listings_delete.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Supprimer l'annonce</h1>

<p>Etes-vous sûr de vouloir supprimer l'annonce " {{title.name_title}} " ?</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Supprimer" class="send_del">
</form>

{% endblock %}

04_Paturâge/merchex_django/merchex/listings/templates/listings/listings_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{title.name_title}}</h2>

<ul>
    <li>Description : {{title.description}}</li>
    <li>Année : {{title.year}}</li>
    <li>Type : {{title.get_type_display}}</li>
    <li>Vendu : {{title.sold|yesno}}</li>
    <li>Groupe : {{title.band}}</li>
</ul>

<div class="option">
    <a href="{% url 'listings-change' title.id %}">Modifier cette annonce</a>

    <a href="{% url 'listings-delete' title.id %}">Supprimer cette annonce</a>

    <a href="{% url 'listings-list' %}">Retour vers les annonces disponibles</a>
</div>


{% endblock %}

04_Paturâge/merchex_django/merchex/listings/templates/listings/listings_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Voici la liste des objets à vendre :</h1>

<a href="{% url 'listings-create' %}">Créer une nouvelle annonce</a>

<p class="link"> Il y a actuellement {{titles|length}} objets à vendre : </p>
<ul>
    {% for title in titles %}
    <li>
        <a href="/title/{{ title.id }}/">{{title.name_title}}</a> -
        <a href="{% url 'listings-change' title.id %}">[Modifier]</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}